#!/bin/bash
cd `dirname $0`
mypwd=$PWD

LIST="stat util user jobs"

mkdir $LIST

find ${mypwd}/taurusview/ | sort >/dev/shm/filelist.txt
cd /dev/shm

while read line; do
  pdf2htmlEX --embed-image 0 $line
  base=`basename $line`
  name=${base%.*}
  convert -crop 773x758+10+10 bg1.png ${mypwd}/stat/${name}.png
  convert -crop 603x216+50+948 bg1.png ${mypwd}/util/${name}.png
  convert -crop 600x220+55+1291 bg1.png ${mypwd}/user/${name}.png
  convert -crop 591x223+65+62 bg2.png ${mypwd}/jobs/${name}.png
done < /dev/shm/filelist.txt

# to check output, create video
for FOLDER in $LIST; do
  cd $FOLDER
  mencoder mf://*.png -mf w=800:h=600:fps=25:type=png -ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell -oac copy -o output.avi
  cd ..
done

